name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Push the Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: fabricioveronez/k8s-dashboard-csharp
        tags: latest, v1
        dockerfile: ./src/KubernetesApi.Web/Dockerfile
        path: ./src/
        